apiVersion: v1
kind: Service
metadata:
  name: service-alpine-k8s-tools-7777-1234
spec:
  #type: NodePort
  #externalTrafficPolicy: Cluster
  type: ClusterIP
  selector:
    app: frontendpod-1234 
  ports: 
    - protocol: TCP
      port: 7777
      targetPort: 1234
