apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: k8straining-deployments-ingress

resources:
- overlays/project1/back
- overlays/project1/front

labels:
- includeSelectors: true
  pairs:
    context: k8straining
