apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendpod-4444
  labels:
    app: backendpod-4444 
  #namespace: project2ns 
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: backendpod-4444 
  template:
    metadata:
      labels:
        app: backendpod-4444 
        project: project2
        netzone: backend
    spec:
      containers:
      - name: backendpod-4444 
        imagePullPolicy: Always
        #imagePullPolicy: IfNotPresent
        image: docker.io/byte13/alpine-k8s-tools
        ports:
        - containerPort: 4444
        command: [ "/K8SLAB/ncwebsrv.sh", "4444" ]
        #command: [ "/bin/bash", "-c", "--" ]
        #args: [ "while true; do cat /B13/HTML/index.html | nc -l -p 4444; done" ]
        # Just spin & wait forever doing nothing usefull
        #args: [ "while true; do sleep 30; done" ]
      nodeSelector:
        kubernetes.io/hostname: winux042.lab.byte13.org
