apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: busybox
    b13tag: busybox-6666
  name: busybox-6666 
  namespace: b13-ns3
spec:
  replicas: 2
  selector:
    matchLabels:
      run: busybox
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: busybox
    spec:
      nodeSelector:
        kubernetes.io/hostname: winux044.lab.byte13.org
      containers:
      - image: quay.io/quay/busybox:latest
        imagePullPolicy: Always
        name: busybox-6666 
        command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]
        ports:
        - containerPort: 6666
      securityContext:
        runAsUser: 0
      terminationGracePeriodSeconds: 30
