apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendpod-3333
  labels:
    app: frontendpod-3333 
  #namespace: project2ns 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontendpod-3333 
  template:
    metadata:
      labels:
        app: frontendpod-3333 
        project: project2
        netzone: frontend
    spec:
      containers:
      - name: frontendpod-3333 
        #imagePullPolicy: Always
        imagePullPolicy: IfNotPresent
        image: docker.io/byte13/alpine-k8s-tools
        ports:
        - containerPort: 3333
        command: [ "/K8SLAB/ncwebsrv.sh", "3333" ]
        #command: [ "/bin/bash", "-c", "--" ]
        #args: [ "while true; do cat /B13/HTML/index.html | nc -l -p 3333; done" ]
        # Just spin & wait forever doing nothing usefull
        #args: [ "while true; do sleep 30; done" ]
      nodeSelector:
        kubernetes.io/hostname: k8sworker11.lab.byte13.org
