apiVersion: v1
kind: Pod
metadata:
  name: frontendpod-1234-b
  labels:
    app: frontendpod-1234
spec:
  containers:
  - name: frontendpod-1234-b
    image: docker.io/byte13/alpine-k8s-tools 
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 1234
    command: [ "/K8SLAB/ncwebsrv.sh", "1234" ]
