apiVersion: v1
kind: Pod
metadata:
  name: backendpod-4444 
  labels:
    app: backendpod-4444 
spec:
  containers:
  - name: backendpod-4444 
    image: docker.io/byte13/alpine-k8s-tools 
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 4444
    command: [ "/K8SLAB/ncwebsrv.sh", "4444" ]
    #securityContext:
    #  privileged: true
  nodeSelector:
    kubernetes.io/hostname: k8sworker12.lab.byte13.org
