apiVersion: v1
kind: Service
metadata:
  name: b13-alpine-nettools-1111
  namespace: b13-ns1
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  selector:
    app: b13-alpine-nettools-1111
  ports: 
    - protocol: TCP
      port: 1111
      targetPort: 1111
