apiVersion: v1
kind: Service
metadata:
  name: service-alpine-k8s-tools-2222
  #namespace: default
spec:
  #type: NodePort
  #externalTrafficPolicy: Cluster
  type: ClusterIP
  selector:
    app: backendpod-2222 
  ports: 
    - protocol: TCP
      port: 2222
      targetPort: 2222
