apiVersion: v1
kind: Service
metadata:
  name: b13-alpine-nettools-4444
  namespace: b13-ns2
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  selector:
    app: b13-alpine-nettools-4444
  ports: 
    - protocol: TCP
      port: 4444
      targetPort: 4444
