apiVersion: v1
kind: Service
metadata:
  name: b13-alpine-nettools-2222
  namespace: b13-ns2
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  selector:
    app: b13-alpine-nettools-2222
  ports: 
    - protocol: TCP
      port: 2222
      targetPort: 2222
