apiVersion: v1
kind: Service
metadata:
  name: nodered-service
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  selector:
    app: nodered
  ports: 
    - protocol: TCP
      port: 8888
      targetPort: 1880
