apiVersion: v1
kind: Service
metadata:
  name: b13-alpine-nettools-3333
  namespace: b13-ns1
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  selector:
    app: b13-alpine-nettools-3333
  ports: 
    - protocol: TCP
      port: 3333
      targetPort: 3333
