apiVersion: configuration.konghq.com/v1
kind: KongPlugin
plugin: ip-restriction 
metadata:
 name: ipr-frontend-1111 
 annotations:
   kubernetes.io/gateway.class: kong
config:
    allow:
    - 10.13.3.3/32 
    #- 10.100.221.64/32
    #deny:
    #- 0.0.0.0/0

