apiVersion: configuration.konghq.com/v1
kind: KongPlugin
plugin: ip-restriction 
metadata:
 name: ipr-test-network-only
 annotations:
   kubernetes.io/gateway.class: kong
config:
    allow:
    - 10.13.3.3/32 
    - 10.100.143.128/32
    #deny:
    #- 0.0.0.0/0

