apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway-project1
  namespace: project1-gw-ns
  annotations:
    # Next line active IP restriction plugin named rule
    #konghq.com/plugins: ipr-clients-1111 
spec:
  gatewayClassName: gwclass-kong
  listeners:
  - name: kong-http 
    port: 80 
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            projectname: project1ns
