apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    audit2rbac.liggitt.net/version: v0.10.0
  labels:
    audit2rbac.liggitt.net/generated: "true"
    audit2rbac.liggitt.net/user: johndev1
  name: audit2rbac:johndev1
  namespace: project22ns
rules:
- apiGroups:
  - ""
  resourceNames:
  - frontendpod-1111
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - ""
  resourceNames:
  - service-alpine-k8s-tools-1111
  resources:
  - services
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    audit2rbac.liggitt.net/version: v0.10.0
  labels:
    audit2rbac.liggitt.net/generated: "true"
    audit2rbac.liggitt.net/user: johndev1
  name: audit2rbac:johndev1
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    audit2rbac.liggitt.net/version: v0.10.0
  labels:
    audit2rbac.liggitt.net/generated: "true"
    audit2rbac.liggitt.net/user: johndev1
  name: audit2rbac:johndev1
  namespace: project22ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: audit2rbac:johndev1
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: johndev1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    audit2rbac.liggitt.net/version: v0.10.0
  labels:
    audit2rbac.liggitt.net/generated: "true"
    audit2rbac.liggitt.net/user: johndev1
  name: audit2rbac:johndev1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: audit2rbac:johndev1
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: johndev1
