apiVersion: v1
kind: Service
metadata:
  name: service-petstore-8080 
  annotations:
    konghq.com/plugins: 'oas-validation-petstore,ip-restriction'
spec:
  #type: NodePort
  #externalTrafficPolicy: Cluster
  type: ClusterIP
  selector:
    app: petstore-8080 
  ports: 
    - protocol: TCP
      port: 8080
      targetPort: 8080
