apiVersion: v1
kind: Pod
metadata:
  name: backendpod-2222 
  labels:
    app: backendpod-2222 
  namespace: project1ns
spec:
  containers:
  - name: backendpod-2222 
    image: docker.io/byte13/alpine-k8s-tools 
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 2222
    command: [ "/K8SLAB/ncwebsrv.sh", "2222" ]
    #securityContext:
    #  privileged: true
  nodeSelector:
    kubernetes.io/hostname: k8sworker12.lab.byte13.org
