apiVersion: v1
kind: Service
metadata:
  name: service-alpine-k8s-tools-1111
  namespace: project1ns
spec:
  #type: NodePort
  #externalTrafficPolicy: Cluster
  #externalTrafficPolicy: Local
  type: ClusterIP
  selector:
    app: frontendpod-1111 
  ports: 
    - protocol: TCP
      port: 1111
      targetPort: 1111
