apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-local-path1 
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOncePod 
  hostPath:
    path: "/B13/PV-LOCAL"

