apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb-allowall
  #namespace: default
subjects:
  - kind: Group
    name: allprojects 
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name:  cr-allow-all
  apiGroup: ""
