apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb-secofficer
  #namespace: default
subjects:
  - kind: Group
    name: secgroup1 
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name:  cr-secofficer
  apiGroup: ""
