kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding-allow-all 
  #namespace: default 
subjects:
  - kind: User
    name: jackadm1
roleRef:
  kind: Role
  name: role-allow-all
  apiGroup: rbac.authorization.k8s.io
