apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb-appsdev 
  #namespace: default
subjects:
  - kind: Group
    name: devgroup1 
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name:  cr-appsdev
  apiGroup: ""
