apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb-infraengineer 
  #namespace: default
subjects:
  - kind: Group
    name: infragroup1 
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name:  cr-infraengineer
  apiGroup: ""
