apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cr-appsdev
# namespace: default
rules:
  - apiGroups: [""]
    resources: ["namespaces", "pods"]
    verbs: ["create", "get", "list", "watch", "view"]
