apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: project1-back

resources:
  - ../../../base/

namespace: project1ns

patches:
  # Strategic merge patch format
  #- patch: |-
  #    apiVersion: apps/v1
  #    kind: Deployment
  #    metadata:
  #      name: frontendpod-
  #    spec:

  # Json 6902 patch format
  # https://datatracker.ietf.org/doc/html/rfv6902
  - target:
      kind: Deployment
      name: dpl

    patch: |-
      - op: replace
        path: /metadata/name
        value: depl-backend-2222
      - op: replace
        path: /metadata/labels/appname
        value: app-backend-2222
      - op: replace
        path: /spec/selector/matchLabels/app
        value: pod-backend-2222
      - op: replace
        path: /spec/template/metadata/labels/app
        value: pod-backend-2222
      - op: replace
        path: /spec/template/metadata/labels/netzone
        value: frontend
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: cnt-backend-2222
      - op: replace
        path: /spec/template/spec/containers/0/ports/0
        value:
          containerPort: 2222
      - op: replace
        path: /spec/template/spec/containers/0/command/1
        value: 2222

  - target:
      kind: Service
      name: svc

    patch: |-
      - op: replace
        path: /metadata/name
        value: svc-backend-2222
      - op: replace
        path: /spec/selector/app
        value: app-backend-2222
      - op: replace
        path: /spec/ports/0
        value:
          port: 2222
          targetPort: 2222
      

  - target:
      kind: Ingress
      name: ingress-ipfilter

    patch: |-
      - op: replace
        path: /metadata/name
        value: ingress-ipfilter-backend-2222
      - op: replace
        path: /spec/rules/0/http/paths/0/path
        value: /frontend-2222
      - op: replace
        path: /spec/rules/0/http/paths/0/backend/service/name
        value: svc-backend-2222
