apiVersion: v1
kind: Pod

metadata:
  name: frontendpod-very-unprivileged-5555
  labels:
    app: frontendpod-very-unprivileged-5555 
    netzone: frontend

spec:
  containers:
  - name: frontendpod-very-unprivileged-5555 
    #imagePullPolicy: Always
    imagePullPolicy: IfNotPresent
    image: docker.io/byte13/alpine-k8s-tools
    ports:
    - containerPort: 5555
    command: [ "/K8SLAB/ncwebsrv.sh", "5555" ]

    securityContext:
        runAsUser: 1234
        privileged: false
        allowPrivilegeEscalation: false
        capabilities:
          drop:
           - ALL

  nodeSelector:
    kubernetes.io/hostname: k8sworker11.lab.byte13.org
