apiVersion: v1
kind: Pod
metadata:
  name: frontendpod-capabilities-5555
  labels:
    app: frontendpod-capabilities-5555
    netzone: frontend

spec:
  containers:
  - name: frontendpod-capabilities-5555
    #imagePullPolicy: Always
    imagePullPolicy: IfNotPresent
    image: docker.io/byte13/alpine-k8s-tools
    ports:
    - containerPort: 5555
    command: [ "/K8SLAB/ncwebsrv.sh", "5555" ]

    securityContext:
      capabilities:
        # Just to ping :-)
        #add: ["NET_RAW"]
        add: ["NET_BIND_SERVICE"]
             # Other examples :
             #   CAP_SYS_TIME
             #       Set system clock 
             #   CAP_SYS_ADMIN
             #       Almighty capabilities
             #   CAP_NET_BIND_SERVICE
             #       Bind a socket to Internet domain privileged ports (port numbers less than 1024)
             #   CAP_CHOWN
             #       Make arbitrary changes to file UIDs and GIDs
             #   CAP_FOWNER
             #       Bypass permission checks on operations that normally require the filesystem UID 
             #       of the process to match the UID of the file 
             #   etc. Please, do "man capabilities" for a full list of Linux kernel capabilities 
            
  nodeSelector:
    kubernetes.io/hostname: k8sworker11.lab.byte13.org
