apiVersion: v1
kind: Pod
metadata:
  name: frontendpod-apparmor-5555
  labels:
    app: frontendpod-apparmor-5555
    netzone: frontend

spec:
  containers:
  - name: frontendpod-apparmor-5555
    #imagePullPolicy: Always
    imagePullPolicy: IfNotPresent
    image: docker.io/byte13/alpine-k8s-tools
    ports:
    - containerPort: 5555
    command: [ "/K8SLAB/ncwebsrv.sh", "5555" ]

  securityContext:
    seccompProfile:
      type: Localhost
      localhostProfile: profiles/audit.json

  nodeSelector:
    kubernetes.io/hostname: k8sworker11.lab.byte13.org
