apiVersion: v1
kind: Pod

metadata:
  name: frontendpod-selinux-5555
  labels:
    app: frontendpod-selinux-5555
    netzone: frontend

spec:
  containers:
  - name: frontendpod-selinux-5555 
    image: docker.io/byte13/alpine-k8s-tools
    #imagePullPolicy: Always
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 5555
    command: [ "/K8SLAB/ncwebsrv.sh", "5555" ]

    securityContext:
      seLinuxOptions:
        level: "s0:c123,c456"
          
  nodeSelector:
    kubernetes.io/hostname: k8sworker11.lab.byte13.org
