apiVersion: v1
kind: Pod

metadata:
  name: frontendpod-privileged-5555
  labels:
    app: frontendpod-privileged-5555
    netzone: frontend

spec:
  containers:
  - name: frontendpod-privileged-5555
    #imagePullPolicy: Always
    imagePullPolicy: IfNotPresent
    image: docker.io/byte13/alpine-k8s-tools-uidset
    ports:
    - containerPort: 5555
    command: [ "/K8SLAB/ncwebsrv.sh", "5555" ]

    securityContext:
      privileged: true
          
  nodeSelector:
    kubernetes.io/hostname: k8sworker11.lab.byte13.org
