apiVersion: v1
kind: Pod

metadata:
  name: frontendpod-selinux-hostvol-5555
  labels:
    app: frontendpod-selinux-hostvol-5555 
    netzone: frontend

spec:
  containers:
  - name: frontendpod-selinux-hostvol-5555 
    #imagePullPolicy: Always
    imagePullPolicy: IfNotPresent
    image: docker.io/byte13/alpine-k8s-tools
    ports:
    - containerPort: 5555
    command: [ "/K8SLAB/ncwebsrv.sh", "5555" ]

    securityContext:
      runAsUser: 1234
      runAsGroup: 4321

      seLinuxOptions:
        type: "frontendpod-selinux-hostvol-5555.process"
        level: "s0:c123,c456"

    volumeMounts:
    - mountPath: /K8SHOSTDIR
      name: vol-host-k8slab
  volumes:
  - name: vol-host-k8slab 
    hostPath:
      # directory location on host
      path: /K8SLAB
      type: DirectoryOrCreate
      #type: Directory
          
  nodeSelector:
    kubernetes.io/hostname: k8sworker11.lab.byte13.org
