apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendpod-selinux-5555
  labels:
    app: frontendpod-selinux-5555
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: frontendpod-selinux-5555 
  template:
    metadata:
      labels:
        app: frontendpod-selinux-5555 
        project: project3
        netzone: frontend
    spec:
      containers:
      - name: frontendpod-selinux-5555 
        imagePullPolicy: Always
        #imagePullPolicy: IfNotPresent
        image: docker.io/byte13/alpine-k8s-tools
        ports:
        - containerPort: 5555
        command: [ "/K8SLAB/ncwebsrv.sh", "5555" ]
        #args: [ "while true; do cat /B13/HTML/index.html | nc -l -p 5555; done" ]

        securityContext:
          seLinuxOptions:
            level: "s0:c123:c456"
              
      nodeSelector:
        kubernetes.io/hostname: k8sworker11.lab.byte13.org
