apiVersion: v1
kind: Pod

metadata:
  name: frontendpod-uid-gid-fsgroup-multicontainer
  labels:
    app: frontendpod-uid-gid-fsgroup-multicontainer
spec:

  securityContext:
    runAsUser: 1234
    runAsGroup: 4321
    fsGroup: 2000

  containers:
  - name: frontendpod-capabilities-5555 
    image: docker.io/byte13/alpine-k8s-tools 
    ports:
    - containerPort: 5555
    command: [ "/K8SLAB/ncwebsrv.sh", "5555" ]
    securityContext:
      capabilities:
        add:
          - CAP_NET_RAW

  - name: frontendpod-6666 
    image: docker.io/byte13/alpine-k8s-tools
    ports:
    - containerPort: 6666
    command: [ "/K8SLAB/ncwebsrv.sh", "6666" ]

  - name: frontendpod-privileged-7777 
    image: docker.io/byte13/alpine-k8s-tools
    ports:
    - containerPort: 7777
    command: [ "/K8SLAB/ncwebsrv.sh", "7777" ]
    securityContext:
      privileged: true

  nodeSelector:
    kubernetes.io/hostname: k8sworker11.lab.byte13.org
