apiVersion: v1
kind: Pod
metadata:
  name: frontendpod-3333 
  labels:
    app: frontendpod-3333 
  namespace: project2ns
spec:
  containers:
  - name: frontendpod-3333 
    image: docker.io/byte13/alpine-k8s-tools 
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 3333
    command: [ "/K8SLAB/ncwebsrv.sh", "3333" ]
    securityContext:
      privileged: true
  nodeSelector:
    kubernetes.io/hostname: k8sworker11.lab.byte13.org
