apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }} 
  namespace: {{ .Values.service.namespaceName }} 
spec:
  #type: NodePort
  #externalTrafficPolicy: Cluster
  #externalTrafficPolicy: Local
  type: {{ .Values.service.type }} 
  selector:
    app: {{ .Values.service.selector.app }} 
  ports: 
    - protocol: TCP
      port: {{ .Values.service.port }} 
      targetPort: {{ .Values.service.targetPort }} 
